debian/rules: don't fail in patch if the patches are already applied
Also create the patch stamp in the same way as the other stamp files
(closes: #498327).  Thanks, Petr Salinger!

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -75,17 +75,20 @@ $(STAMP_DIR)/prepare: $(STAMP_DIR)/stampdir
 .PHONY: patch
 patch: $(STAMP_DIR)/patch
 $(STAMP_DIR)/patch: $(STAMP_DIR)/prepare
-	@echo -n "Applying patches... "
-	@if $(QUILT) push -a -v > $(STAMP_DIR)/log/patch 2>&1; then \
-	  cat $(STAMP_DIR)/log/patch; \
-	  echo "successful."; \
+	if $(QUILT) next >/dev/null 2>&1; then \
+	  echo -n "Applying patches... "; \
+	  if $(QUILT) push -a -v > $(STAMP_DIR)/log/patch 2>&1; then \
+	    cat $(STAMP_DIR)/log/patch; \
+	    echo "successful."; \
+	  else \
+	    cat $(STAMP_DIR)/log/patch; \
+	    echo "failed! (Check $(STAMP_DIR)/log/patch for details)"; \
+	    exit 1; \
+	  fi; \
 	else \
-	  cat $(STAMP_DIR)/log/patch; \
-	  echo "failed! (Check $(STAMP_DIR)/log/patch for details)"; \
-	  exit 1; \
-	fi; \
-
-	touch $@
+	  echo "No patches to apply"; \
+	fi
+	>$@
 
 # Revert all patches to the upstream source.
 .PHONY: unpatch
